FROM alpine

RUN apk add git-daemon

RUN mkdir -p /srv/git/repo.git
RUN cd /srv/git/repo.git && git init --bare -b main .
# RUN cd /srv/git/repo.git && echo 'Hello world!' > README.md && git add . && git commit -m 'Initial commit'

CMD ["/usr/libexec/git-core/git-daemon", "--export-all", "--base-path=/srv/git", "--verbose", "--informative-errors", "--enable=receive-pack", "--listen=0.0.0.0", "--port=9418", "/srv/git"]